### ISSUE TITLE
Missing Order instance for ByteVector and BitVector

### ISSUE THREAD

**Issue by sideeffffect** [scodec/scodec-cats#13]
There is no `Order[ByteVector]` nor `Order[BitVector]` present in `scodec-cats`.
Are there any other types in `scodec` which should have `Order` instance @mpilquist ?

**Comment by mpilquist** [comment]
Could they implement `Ordered` instead and pick up the ordering instance as a result?

**Comment by sideeffffect** [comment]
I think this can be closed

**Comment by sideeffffect** [comment]
Actually, `Order[ByteVector]` doesn't seem to get automatically derived, even with `import cats.implicits._`, I still have to manually call `Order.fromOrdering`
```scala
implicit val orderingByteVector: Order[ByteVector] = Order.fromOrdering
```
(since there's only `catsKernelOrderingForOrder`, not `catsKernelOrderForOrdering`)
In that case I suggest we add `Order[ByteVector]` instance to `scodec-cats`.
What do you think, @mpilquist ?
